// ============================================================
//  English vocabulary cards (English ↔ Russian)
//  Field "es" = English word/phrase, "exEs" = English example
// ============================================================
const c = (id, region, es, ru, emoji, exEs, exRu) => ({ id, region, es, ru, emoji, exEs, exRu });

export const CARDS = [
  // ===== Region 1: Greetings =====
  c('en-s-001', 1, 'hello', 'привет, здравствуй', '👋', 'Hello, how are you?', 'Привет, как дела?'),
  c('en-s-002', 1, 'goodbye', 'пока, до свидания', '👋', 'Goodbye, see you soon!', 'Пока, скоро увидимся!'),
  c('en-s-003', 1, 'good morning', 'доброе утро', '🌅', 'Good morning, everyone!', 'Доброе утро всем!'),
  c('en-s-004', 1, 'good afternoon', 'добрый день', '☀️', 'Good afternoon, sir.', 'Добрый день, сэр.'),
  c('en-s-005', 1, 'good evening', 'добрый вечер', '🌙', 'Good evening! Welcome.', 'Добрый вечер! Добро пожаловать.'),
  c('en-s-006', 1, 'yes', 'да', '✅', 'Yes, of course!', 'Да, конечно!'),
  c('en-s-007', 1, 'no', 'нет', '❌', 'No, thank you.', 'Нет, спасибо.'),
  c('en-s-008', 1, 'thank you', 'спасибо', '🙏', 'Thank you very much!', 'Большое спасибо!'),
  c('en-s-009', 1, "you're welcome", 'пожалуйста (в ответ)', '😊', "You're welcome, no problem.", 'Пожалуйста, без проблем.'),
  c('en-s-010', 1, 'please', 'пожалуйста (просьба)', '🙇', 'A coffee, please.', 'Кофе, пожалуйста.'),
  c('en-s-011', 1, 'sorry', 'извини, прости', '😶', "Sorry, I didn't hear you.", 'Извини, я не расслышал.'),
  c('en-s-012', 1, "I'm sorry", 'мне жаль, сожалею', '😔', "I'm so sorry about that.", 'Мне очень жаль.'),
  c('en-s-013', 1, 'excuse me', 'извините (обращение)', '🙋', 'Excuse me, where is the bathroom?', 'Извините, где туалет?'),
  c('en-s-014', 1, 'speak slowly, please', 'пожалуйста, помедленнее', '🐢', 'Speak slowly, please.', 'Говорите помедленнее, пожалуйста.'),
  c('en-s-015', 1, 'how are you?', 'как дела?', '🤔', 'Hi! How are you today?', 'Привет! Как дела сегодня?'),
  c('en-s-016', 1, "I'm fine", 'я в порядке', '👍', "I'm fine, thanks!", 'Я в порядке, спасибо!'),
  c('en-s-017', 1, 'not so good', 'не очень хорошо', '👎', "I'm not feeling so good today.", 'Мне сегодня нехорошо.'),
  c('en-s-018', 1, 'so-so', 'так себе, более-менее', '🤷', "— How are you? — So-so.", '— Как дела? — Так себе.'),
  c('en-s-019', 1, 'and you?', 'а ты?', '🔄', 'Fine, and you?', 'Хорошо, а ты?'),
  c('en-s-020', 1, 'nice to meet you', 'приятно познакомиться', '🤝', "Nice to meet you, I'm Alex.", 'Приятно познакомиться, я Алекс.'),
  c('en-s-021', 1, "what's your name?", 'как тебя зовут?', '🪪', "What's your name?", 'Как тебя зовут?'),
  c('en-s-022', 1, 'my name is...', 'меня зовут...', '🗣️', 'My name is Kate.', 'Меня зовут Кейт.'),
  c('en-s-023', 1, 'see you later', 'до встречи', '✌️', 'See you later, guys!', 'До встречи, ребята!'),
  c('en-s-024', 1, 'see you tomorrow', 'до завтра', '📅', 'See you tomorrow at work.', 'До завтра на работе.'),
  c('en-s-025', 1, 'of course', 'конечно', '💡', 'Of course, no problem!', 'Конечно, без проблем!'),
  c('en-s-026', 1, 'sure / okay', 'ладно, ок', '👌', "Sure, let's go!", 'Ладно, пошли!'),
  c('en-s-027', 1, "I don't understand", 'я не понимаю', '😕', "Sorry, I don't understand.", 'Извините, я не понимаю.'),
  c('en-s-028', 1, 'do you speak Russian?', 'ты говоришь по-русски?', '🇷🇺', 'Do you speak Russian?', 'Ты говоришь по-русски?'),
  c('en-s-029', 1, 'a little', 'немного', '🤏', 'I speak a little English.', 'Я немного говорю по-английски.'),
  c('en-s-030', 1, 'what?', 'что?', '❓', 'What did you say?', 'Что ты сказал?'),
  c('en-s-031', 1, 'where?', 'где?', '📍', 'Where are you?', 'Ты где?'),
  c('en-s-032', 1, 'when?', 'когда?', '⏰', 'When do you arrive?', 'Когда ты приедешь?'),
  c('en-s-033', 1, 'why?', 'почему?', '🤨', 'Why not?', 'Почему нет?'),
  c('en-s-034', 1, 'how?', 'как?', '🔧', 'How do you say this?', 'Как это сказать?'),
  c('en-s-035', 1, 'how much?', 'сколько?', '🔢', 'How much does it cost?', 'Сколько это стоит?'),
  c('en-s-036', 1, 'help!', 'помогите!', '🆘', 'Help, please!', 'Помогите, пожалуйста!'),
  c('en-s-037', 1, 'cheers!', 'за здоровье!', '🥂', 'Cheers, everyone!', 'За здоровье всех!'),
  c('en-s-038', 1, 'sir', 'сэр, господин', '👨', 'Excuse me, sir.', 'Извините, сэр.'),
  c('en-s-039', 1, "ma'am", 'мэм, госпожа', '👩', "Thank you, ma'am.", 'Спасибо, мэм.'),
  c('en-s-040', 1, 'welcome!', 'добро пожаловать!', '🎉', 'Welcome to our city!', 'Добро пожаловать в наш город!'),

  // ===== Region 2: Numbers, Time =====
  c('en-n-001', 2, 'zero', 'ноль', '0️⃣', 'zero degrees', 'ноль градусов'),
  c('en-n-002', 2, 'one', 'один', '1️⃣', 'one coffee, please', 'один кофе, пожалуйста'),
  c('en-n-003', 2, 'two', 'два', '2️⃣', 'two tickets', 'два билета'),
  c('en-n-004', 2, 'three', 'три', '3️⃣', 'three days', 'три дня'),
  c('en-n-005', 2, 'four', 'четыре', '4️⃣', 'four people', 'четыре человека'),
  c('en-n-006', 2, 'five', 'пять', '5️⃣', 'five dollars', 'пять долларов'),
  c('en-n-007', 2, 'six', 'шесть', '6️⃣', 'six hours', 'шесть часов'),
  c('en-n-008', 2, 'seven', 'семь', '7️⃣', 'seven days', 'семь дней'),
  c('en-n-009', 2, 'eight', 'восемь', '8️⃣', 'eight years', 'восемь лет'),
  c('en-n-010', 2, 'nine', 'девять', '9️⃣', 'nine months', 'девять месяцев'),
  c('en-n-011', 2, 'ten', 'десять', '🔟', 'ten minutes', 'десять минут'),
  c('en-n-012', 2, 'eleven', 'одиннадцать', '🔢', 'eleven dollars', 'одиннадцать долларов'),
  c('en-n-013', 2, 'twelve', 'двенадцать', '🔢', 'twelve months', 'двенадцать месяцев'),
  c('en-n-014', 2, 'twenty', 'двадцать', '🔢', 'twenty minutes', 'двадцать минут'),
  c('en-n-015', 2, 'thirty', 'тридцать', '🔢', 'thirty days', 'тридцать дней'),
  c('en-n-016', 2, 'fifty', 'пятьдесят', '🔢', 'fifty dollars', 'пятьдесят долларов'),
  c('en-n-017', 2, 'one hundred', 'сто', '💯', 'one hundred percent', 'сто процентов'),
  c('en-n-018', 2, 'one thousand', 'тысяча', '🔢', 'one thousand dollars', 'тысяча долларов'),
  c('en-n-019', 2, 'Monday', 'понедельник', '📅', 'See you on Monday.', 'Увидимся в понедельник.'),
  c('en-n-020', 2, 'Tuesday', 'вторник', '📅', 'The meeting is on Tuesday.', 'Встреча во вторник.'),
  c('en-n-021', 2, 'Wednesday', 'среда', '📅', 'See you Wednesday.', 'Увидимся в среду.'),
  c('en-n-022', 2, 'Thursday', 'четверг', '📅', 'See you Thursday.', 'Увидимся в четверг.'),
  c('en-n-023', 2, 'Friday', 'пятница', '🎉', "Thank God it's Friday!", 'Слава богу, пятница!'),
  c('en-n-024', 2, 'Saturday', 'суббота', '😎', "Let's go out on Saturday.", 'Давай выйдем в субботу.'),
  c('en-n-025', 2, 'Sunday', 'воскресенье', '☀️', 'Sunday is my day off.', 'Воскресенье — мой выходной.'),
  c('en-n-026', 2, 'today', 'сегодня', '📆', "What's the date today?", 'Какое сегодня число?'),
  c('en-n-027', 2, 'yesterday', 'вчера', '⏮️', 'I went to the gym yesterday.', 'Я вчера ходил в зал.'),
  c('en-n-028', 2, 'tomorrow', 'завтра', '⏭️', 'See you tomorrow!', 'До завтра!'),
  c('en-n-029', 2, 'morning', 'утро', '🌅', 'Good morning!', 'Доброе утро!'),
  c('en-n-030', 2, 'afternoon', 'день, полдень', '☀️', "Let's meet in the afternoon.", 'Давай встретимся днём.'),
  c('en-n-031', 2, 'evening', 'вечер', '🌆', 'Good evening!', 'Добрый вечер!'),
  c('en-n-032', 2, 'night', 'ночь', '🌙', 'Good night, sleep well!', 'Спокойной ночи!'),
  c('en-n-033', 2, 'hour', 'час', '⏰', 'One hour, please.', 'Один час, пожалуйста.'),
  c('en-n-034', 2, 'minute', 'минута', '⏱️', 'Just one minute!', 'Одну минуту!'),
  c('en-n-035', 2, 'week', 'неделя', '📅', 'See you next week.', 'Увидимся на следующей неделе.'),
  c('en-n-036', 2, 'year', 'год', '🎊', 'Happy New Year!', 'С Новым годом!'),

  // ===== Region 3: Grammar / Basic =====
  c('en-b-001', 3, 'I am', 'я (есть)', '🧑', 'I am from Russia.', 'Я из России.'),
  c('en-b-002', 3, 'you are', 'ты (есть)', '👤', 'You are very kind.', 'Ты очень добрый.'),
  c('en-b-003', 3, 'he is', 'он (есть)', '👨', 'He is my friend.', 'Он мой друг.'),
  c('en-b-004', 3, 'she is', 'она (есть)', '👩', 'She is a doctor.', 'Она врач.'),
  c('en-b-005', 3, 'we are', 'мы (есть)', '👥', 'We are happy.', 'Мы счастливы.'),
  c('en-b-006', 3, 'they are', 'они (есть)', '👫', 'They are my friends.', 'Они мои друзья.'),
  c('en-b-007', 3, 'I have', 'у меня есть', '✋', 'I have a question.', 'У меня есть вопрос.'),
  c('en-b-008', 3, 'I want', 'я хочу', '🙋', 'I want coffee, please.', 'Я хочу кофе, пожалуйста.'),
  c('en-b-009', 3, 'I can', 'я могу', '💪', 'I can speak English.', 'Я могу говорить по-английски.'),
  c('en-b-010', 3, 'I need', 'мне нужно', '📌', 'I need help.', 'Мне нужна помощь.'),
  c('en-b-011', 3, 'I like', 'мне нравится', '❤️', 'I like pizza.', 'Мне нравится пицца.'),
  c('en-b-012', 3, 'I know', 'я знаю', '💡', 'I know this word.', 'Я знаю это слово.'),
  c('en-b-013', 3, 'I go', 'я иду', '🚶', 'I go to work every day.', 'Я хожу на работу каждый день.'),
  c('en-b-014', 3, 'I eat', 'я ем', '🍽️', 'I eat breakfast in the morning.', 'Я завтракаю утром.'),
  c('en-b-015', 3, 'I drink', 'я пью', '🥤', 'I drink coffee every morning.', 'Я пью кофе каждое утро.'),
  c('en-b-016', 3, 'very', 'очень', '‼️', 'Very good!', 'Очень хорошо!'),
  c('en-b-017', 3, 'also / too', 'тоже, также', '➕', 'I also like tea.', 'Я тоже люблю чай.'),
  c('en-b-018', 3, "don't / not", 'не', '🚫', "I don't speak German.", 'Я не говорю по-немецки.'),
  c('en-b-019', 3, 'and', 'и', '&', 'Tea and coffee.', 'Чай и кофе.'),
  c('en-b-020', 3, 'but', 'но', '⚡', 'Nice but expensive.', 'Красиво, но дорого.'),

  // ===== Region 4: Family =====
  c('en-f-001', 4, 'mother', 'мама, мать', '👩', 'My mother is a teacher.', 'Моя мама — учитель.'),
  c('en-f-002', 4, 'father', 'папа, отец', '👨', 'My father is tall.', 'Мой папа высокий.'),
  c('en-f-003', 4, 'brother', 'брат', '👦', 'I have one brother.', 'У меня есть один брат.'),
  c('en-f-004', 4, 'sister', 'сестра', '👧', 'My sister is older than me.', 'Моя сестра старше меня.'),
  c('en-f-005', 4, 'son', 'сын', '👦', 'He is my son.', 'Он мой сын.'),
  c('en-f-006', 4, 'daughter', 'дочь', '👧', 'She is my daughter.', 'Она моя дочь.'),
  c('en-f-007', 4, 'grandmother', 'бабушка', '👵', 'My grandmother is very kind.', 'Моя бабушка очень добрая.'),
  c('en-f-008', 4, 'grandfather', 'дедушка', '👴', 'My grandfather loves fishing.', 'Мой дедушка любит рыбалку.'),
  c('en-f-009', 4, 'uncle', 'дядя', '🧔', 'My uncle lives in London.', 'Мой дядя живёт в Лондоне.'),
  c('en-f-010', 4, 'aunt', 'тётя', '👱‍♀️', 'My aunt bakes delicious cakes.', 'Моя тётя печёт вкусные торты.'),
  c('en-f-011', 4, 'husband', 'муж', '💑', 'My husband is funny.', 'Мой муж смешной.'),
  c('en-f-012', 4, 'wife', 'жена', '💑', 'My wife is beautiful.', 'Моя жена красивая.'),
  c('en-f-013', 4, 'baby', 'малыш, ребёнок', '👶', 'The baby is sleeping.', 'Малыш спит.'),
  c('en-f-014', 4, 'family', 'семья', '👨‍👩‍👧', 'I love my family.', 'Я люблю свою семью.'),
  c('en-f-015', 4, 'parents', 'родители', '👨‍👩‍👧', 'My parents live in Moscow.', 'Мои родители живут в Москве.'),
  c('en-f-016', 4, 'children', 'дети', '👶', 'They have two children.', 'У них двое детей.'),
  c('en-f-017', 4, 'boyfriend', 'парень (в отношениях)', '💑', 'He is my boyfriend.', 'Он мой парень.'),
  c('en-f-018', 4, 'girlfriend', 'девушка (в отношениях)', '💑', 'She is my girlfriend.', 'Она моя девушка.'),
  c('en-f-019', 4, 'friend', 'друг, подруга', '🤝', 'She is my best friend.', 'Она моя лучшая подруга.'),
  c('en-f-020', 4, 'neighbor', 'сосед, соседка', '🏘️', 'My neighbor is very nice.', 'Мой сосед очень приятный.'),

  // ===== Region 5: Food =====
  c('en-c-001', 5, 'water', 'вода', '💧', 'A glass of water, please.', 'Стакан воды, пожалуйста.'),
  c('en-c-002', 5, 'coffee', 'кофе', '☕', 'I drink coffee every morning.', 'Я пью кофе каждое утро.'),
  c('en-c-003', 5, 'tea', 'чай', '🍵', 'Would you like some tea?', 'Хочешь чая?'),
  c('en-c-004', 5, 'juice', 'сок', '🍊', 'Orange juice, please.', 'Апельсиновый сок, пожалуйста.'),
  c('en-c-005', 5, 'milk', 'молоко', '🥛', 'I like cold milk.', 'Я люблю холодное молоко.'),
  c('en-c-006', 5, 'bread', 'хлеб', '🍞', 'Fresh bread is delicious.', 'Свежий хлеб вкусный.'),
  c('en-c-007', 5, 'butter', 'масло', '🧈', 'Bread with butter.', 'Хлеб с маслом.'),
  c('en-c-008', 5, 'cheese', 'сыр', '🧀', 'I love cheese.', 'Я люблю сыр.'),
  c('en-c-009', 5, 'meat', 'мясо', '🥩', 'This meat is very good.', 'Это мясо очень хорошее.'),
  c('en-c-010', 5, 'chicken', 'курица', '🍗', 'Grilled chicken, please.', 'Курица-гриль, пожалуйста.'),
  c('en-c-011', 5, 'fish', 'рыба', '🐟', 'I love fresh fish.', 'Я люблю свежую рыбу.'),
  c('en-c-012', 5, 'rice', 'рис', '🍚', 'Rice with vegetables.', 'Рис с овощами.'),
  c('en-c-013', 5, 'pasta', 'паста, макароны', '🍝', 'Pasta with tomato sauce.', 'Паста с томатным соусом.'),
  c('en-c-014', 5, 'salad', 'салат', '🥗', 'A fresh salad, please.', 'Свежий салат, пожалуйста.'),
  c('en-c-015', 5, 'soup', 'суп', '🍲', 'Hot soup warms you up.', 'Горячий суп согревает.'),
  c('en-c-016', 5, 'apple', 'яблоко', '🍎', 'An apple a day is healthy.', 'Яблоко в день — полезно.'),
  c('en-c-017', 5, 'orange', 'апельсин', '🍊', 'Fresh orange juice.', 'Свежий апельсиновый сок.'),
  c('en-c-018', 5, 'banana', 'банан', '🍌', 'I eat a banana every day.', 'Я ем банан каждый день.'),
  c('en-c-019', 5, 'strawberry', 'клубника', '🍓', 'Strawberries with cream.', 'Клубника со сливками.'),
  c('en-c-020', 5, 'cake', 'торт, пирог', '🎂', 'A piece of cake, please.', 'Кусочек торта, пожалуйста.'),
  c('en-c-021', 5, 'pizza', 'пицца', '🍕', 'Pizza is my favorite food.', 'Пицца — моя любимая еда.'),
  c('en-c-022', 5, 'sandwich', 'бутерброд, сэндвич', '🥪', 'A sandwich with cheese.', 'Бутерброд с сыром.'),
  c('en-c-023', 5, 'egg', 'яйцо', '🥚', 'Fried eggs for breakfast.', 'Яичница на завтрак.'),
  c('en-c-024', 5, 'vegetables', 'овощи', '🥦', 'Fresh vegetables are healthy.', 'Свежие овощи полезны.'),
  c('en-c-025', 5, 'breakfast', 'завтрак', '🍳', 'I eat breakfast at 8.', 'Я завтракаю в 8.'),

  // ===== Region 6: City =====
  c('en-ci-001', 6, 'street', 'улица', '🛣️', 'Which street is this?', 'Какая это улица?'),
  c('en-ci-002', 6, 'house', 'дом, здание', '🏠', 'I live in a big house.', 'Я живу в большом доме.'),
  c('en-ci-003', 6, 'bus', 'автобус', '🚌', 'Take the bus number 5.', 'Садитесь на автобус №5.'),
  c('en-ci-004', 6, 'car', 'машина', '🚗', 'I go by car.', 'Я еду на машине.'),
  c('en-ci-005', 6, 'subway', 'метро', '🚇', 'Take the subway downtown.', 'Доехать на метро до центра.'),
  c('en-ci-006', 6, 'taxi', 'такси', '🚕', 'Call a taxi, please.', 'Вызовите такси, пожалуйста.'),
  c('en-ci-007', 6, 'airport', 'аэропорт', '✈️', 'The airport is far.', 'Аэропорт далеко.'),
  c('en-ci-008', 6, 'hotel', 'отель, гостиница', '🏨', 'I need a hotel room.', 'Мне нужен номер в отеле.'),
  c('en-ci-009', 6, 'restaurant', 'ресторан', '🍽️', "Let's go to a restaurant.", 'Давай пойдём в ресторан.'),
  c('en-ci-010', 6, 'café', 'кафе', '☕', "Let's meet at the café.", 'Давай встретимся в кафе.'),
  c('en-ci-011', 6, 'store / shop', 'магазин', '🛍️', 'The store is closed.', 'Магазин закрыт.'),
  c('en-ci-012', 6, 'school', 'школа', '🏫', 'My school is nearby.', 'Моя школа рядом.'),
  c('en-ci-013', 6, 'hospital', 'больница', '🏥', 'The hospital is on Main Street.', 'Больница на Главной улице.'),
  c('en-ci-014', 6, 'bank', 'банк', '🏦', 'I need to go to the bank.', 'Мне нужно в банк.'),
  c('en-ci-015', 6, 'park', 'парк', '🌳', "Let's walk in the park.", 'Давай прогуляемся в парке.'),
  c('en-ci-016', 6, 'pharmacy', 'аптека', '💊', 'Is there a pharmacy nearby?', 'Есть поблизости аптека?'),
  c('en-ci-017', 6, 'left', 'налево, слева', '⬅️', 'Turn left here.', 'Поверни налево здесь.'),
  c('en-ci-018', 6, 'right', 'направо, справа', '➡️', 'The bank is on the right.', 'Банк справа.'),
  c('en-ci-019', 6, 'straight ahead', 'прямо', '⬆️', 'Go straight ahead.', 'Иди прямо.'),
  c('en-ci-020', 6, 'near / close', 'близко, рядом', '📍', "It's very close.", 'Это очень близко.'),

  // ===== Region 7: Shopping =====
  c('en-sh-001', 7, 'to buy', 'купить', '🛒', 'I want to buy a shirt.', 'Я хочу купить рубашку.'),
  c('en-sh-002', 7, 'price', 'цена', '💰', "What's the price?", 'Какая цена?'),
  c('en-sh-003', 7, 'expensive', 'дорогой', '💸', 'This is too expensive.', 'Это слишком дорого.'),
  c('en-sh-004', 7, 'cheap', 'дешёвый, недорогой', '🤑', 'This is very cheap!', 'Это очень дёшево!'),
  c('en-sh-005', 7, 'size', 'размер', '📏', "What's your size?", 'Какой у тебя размер?'),
  c('en-sh-006', 7, 'small', 'маленький', '🔽', 'This is too small.', 'Это слишком маленькое.'),
  c('en-sh-007', 7, 'large', 'большой', '🔼', 'Do you have a larger size?', 'Есть размер побольше?'),
  c('en-sh-008', 7, 'black', 'чёрный', '⚫', 'I like black shoes.', 'Мне нравятся чёрные туфли.'),
  c('en-sh-009', 7, 'white', 'белый', '⚪', 'A white dress.', 'Белое платье.'),
  c('en-sh-010', 7, 'red', 'красный', '🔴', 'A red coat.', 'Красное пальто.'),
  c('en-sh-011', 7, 'blue', 'синий, голубой', '🔵', 'A blue jacket.', 'Синяя куртка.'),
  c('en-sh-012', 7, 'green', 'зелёный', '🟢', 'Green shoes.', 'Зелёные туфли.'),
  c('en-sh-013', 7, 'yellow', 'жёлтый', '🟡', 'A yellow bag.', 'Жёлтая сумка.'),
  c('en-sh-014', 7, 't-shirt', 'футболка', '👕', 'I need a new t-shirt.', 'Мне нужна новая футболка.'),
  c('en-sh-015', 7, 'pants / trousers', 'штаны, брюки', '👖', 'These pants fit well.', 'Эти брюки хорошо сидят.'),
  c('en-sh-016', 7, 'dress', 'платье', '👗', 'A beautiful dress.', 'Красивое платье.'),
  c('en-sh-017', 7, 'shoes', 'туфли, обувь', '👟', 'New shoes for the party.', 'Новые туфли на вечеринку.'),
  c('en-sh-018', 7, 'jacket', 'куртка, пиджак', '🧥', 'A warm jacket.', 'Тёплая куртка.'),
  c('en-sh-019', 7, 'bag', 'сумка', '👜', 'A leather bag.', 'Кожаная сумка.'),
  c('en-sh-020', 7, 'discount', 'скидка', '🏷️', 'Is there a discount?', 'Есть скидка?'),

  // ===== Region 8: Home =====
  c('en-h-001', 8, 'apartment', 'квартира', '🏢', 'I live in an apartment.', 'Я живу в квартире.'),
  c('en-h-002', 8, 'room', 'комната', '🚪', 'This is a big room.', 'Это большая комната.'),
  c('en-h-003', 8, 'bedroom', 'спальня', '🛏️', 'The bedroom is quiet.', 'Спальня тихая.'),
  c('en-h-004', 8, 'bathroom', 'ванная, туалет', '🚿', 'Where is the bathroom?', 'Где ванная?'),
  c('en-h-005', 8, 'kitchen', 'кухня', '🍳', 'I cook in the kitchen.', 'Я готовлю на кухне.'),
  c('en-h-006', 8, 'living room', 'гостиная', '🛋️', "Let's sit in the living room.", 'Давай посидим в гостиной.'),
  c('en-h-007', 8, 'table', 'стол', '🪑', 'The keys are on the table.', 'Ключи на столе.'),
  c('en-h-008', 8, 'chair', 'стул', '🪑', 'Please sit on this chair.', 'Пожалуйста, садитесь на этот стул.'),
  c('en-h-009', 8, 'bed', 'кровать', '🛏️', 'The bed is comfortable.', 'Кровать удобная.'),
  c('en-h-010', 8, 'window', 'окно', '🪟', 'Open the window, please.', 'Открой окно, пожалуйста.'),
  c('en-h-011', 8, 'door', 'дверь', '🚪', 'Close the door.', 'Закрой дверь.'),
  c('en-h-012', 8, 'floor', 'пол', '⬛', 'The floor is clean.', 'Пол чистый.'),
  c('en-h-013', 8, 'refrigerator', 'холодильник', '🧊', "The milk's in the fridge.", 'Молоко в холодильнике.'),
  c('en-h-014', 8, 'stove', 'плита', '🔥', 'Cook on the stove.', 'Готовь на плите.'),
  c('en-h-015', 8, 'shower', 'душ', '🚿', 'I take a shower every morning.', 'Я принимаю душ каждое утро.'),
  c('en-h-016', 8, 'sofa / couch', 'диван', '🛋️', 'Sit on the sofa.', 'Садись на диван.'),
  c('en-h-017', 8, 'lamp', 'лампа', '💡', 'Turn on the lamp.', 'Включи лампу.'),
  c('en-h-018', 8, 'television', 'телевизор', '📺', "What's on TV tonight?", 'Что сегодня по телевизору?'),
  c('en-h-019', 8, 'keys', 'ключи', '🔑', "I can't find my keys.", 'Я не могу найти свои ключи.'),
  c('en-h-020', 8, 'wall', 'стена', '🧱', 'The picture is on the wall.', 'Картина на стене.'),

  // ===== Region 9: Body / Health =====
  c('en-cu-001', 9, 'head', 'голова', '🗣️', 'My head hurts.', 'У меня болит голова.'),
  c('en-cu-002', 9, 'hair', 'волосы', '💇', 'She has beautiful hair.', 'У неё красивые волосы.'),
  c('en-cu-003', 9, 'eye', 'глаз', '👁️', 'Blue eyes.', 'Голубые глаза.'),
  c('en-cu-004', 9, 'ear', 'ухо', '👂', 'I hear with my ears.', 'Я слышу ушами.'),
  c('en-cu-005', 9, 'nose', 'нос', '👃', 'My nose is cold.', 'У меня холодный нос.'),
  c('en-cu-006', 9, 'mouth', 'рот', '👄', 'Open your mouth.', 'Открой рот.'),
  c('en-cu-007', 9, 'tooth', 'зуб', '🦷', 'My tooth hurts.', 'У меня болит зуб.'),
  c('en-cu-008', 9, 'hand', 'рука', '✋', 'Wash your hands.', 'Помой руки.'),
  c('en-cu-009', 9, 'leg', 'нога', '🦵', 'My legs are tired.', 'Мои ноги устали.'),
  c('en-cu-010', 9, 'back', 'спина', '🔙', 'My back hurts.', 'У меня болит спина.'),
  c('en-cu-011', 9, 'stomach', 'живот', '🫁', 'I have a stomachache.', 'У меня болит живот.'),
  c('en-cu-012', 9, 'heart', 'сердце', '❤️', 'A healthy heart.', 'Здоровое сердце.'),
  c('en-cu-013', 9, 'doctor', 'врач', '👨‍⚕️', 'I need to see a doctor.', 'Мне нужно к врачу.'),
  c('en-cu-014', 9, 'medicine', 'лекарство', '💊', 'Take this medicine.', 'Прими это лекарство.'),
  c('en-cu-015', 9, 'pain', 'боль', '😣', 'I feel pain here.', 'Здесь больно.'),
  c('en-cu-016', 9, 'fever', 'жар, температура', '🤒', 'I have a fever.', 'У меня жар.'),
  c('en-cu-017', 9, 'cold', 'простуда', '🤧', 'I have a cold.', 'У меня простуда.'),
  c('en-cu-018', 9, 'headache', 'головная боль', '🤕', 'I have a headache.', 'У меня болит голова.'),
  c('en-cu-019', 9, 'I feel good', 'я чувствую себя хорошо', '😊', 'I feel great today!', 'Сегодня я чувствую себя отлично!'),
  c('en-cu-020', 9, 'I feel sick', 'мне плохо', '🤢', 'I feel sick, I need rest.', 'Мне плохо, нужен отдых.'),
  c('en-cu-021', 9, 'tired', 'усталый', '😴', "I'm very tired.", 'Я очень устал.'),
  c('en-cu-022', 9, 'healthy', 'здоровый', '💪', 'Stay healthy!', 'Будь здоров!'),
  c('en-cu-023', 9, 'nurse', 'медсестра, медбрат', '👩‍⚕️', 'The nurse is very kind.', 'Медсестра очень добрая.'),
  c('en-cu-024', 9, 'appointment', 'запись, встреча', '📋', "I have a doctor's appointment.", 'У меня запись к врачу.'),
  c('en-cu-025', 9, 'pharmacy', 'аптека', '💊', 'I need to go to the pharmacy.', 'Мне нужно в аптеку.'),

  // ===== Region 10: Nature =====
  c('en-na-001', 10, 'tree', 'дерево', '🌳', 'A big tree in the park.', 'Большое дерево в парке.'),
  c('en-na-002', 10, 'flower', 'цветок', '🌸', 'Beautiful flowers.', 'Красивые цветы.'),
  c('en-na-003', 10, 'grass', 'трава', '🌿', 'Green grass.', 'Зелёная трава.'),
  c('en-na-004', 10, 'river', 'река', '🏞️', 'The river is long.', 'Река длинная.'),
  c('en-na-005', 10, 'sea / ocean', 'море, океан', '🌊', 'I love the sea.', 'Я люблю море.'),
  c('en-na-006', 10, 'mountain', 'гора', '⛰️', 'The mountains are high.', 'Горы высокие.'),
  c('en-na-007', 10, 'sky', 'небо', '☁️', 'The sky is blue.', 'Небо голубое.'),
  c('en-na-008', 10, 'sun', 'солнце', '☀️', 'The sun is shining.', 'Солнце светит.'),
  c('en-na-009', 10, 'moon', 'луна', '🌙', 'A full moon tonight.', 'Сегодня полная луна.'),
  c('en-na-010', 10, 'star', 'звезда', '⭐', 'I see many stars.', 'Я вижу много звёзд.'),
  c('en-na-011', 10, 'rain', 'дождь', '🌧️', "It's raining outside.", 'На улице идёт дождь.'),
  c('en-na-012', 10, 'snow', 'снег', '❄️', 'The snow is beautiful.', 'Снег красивый.'),
  c('en-na-013', 10, 'wind', 'ветер', '💨', 'Strong wind today.', 'Сильный ветер сегодня.'),
  c('en-na-014', 10, 'hot', 'жаркий', '🔥', "It's very hot today.", 'Сегодня очень жарко.'),
  c('en-na-015', 10, 'cold', 'холодный', '🧊', "It's very cold outside.", 'На улице очень холодно.'),
  c('en-na-016', 10, 'warm', 'тёплый', '🌤️', 'A warm spring day.', 'Тёплый весенний день.'),
  c('en-na-017', 10, 'spring', 'весна', '🌷', 'Spring is my favorite season.', 'Весна — мой любимый сезон.'),
  c('en-na-018', 10, 'summer', 'лето', '☀️', 'Hot summer days.', 'Жаркие летние дни.'),
  c('en-na-019', 10, 'autumn / fall', 'осень', '🍂', 'Beautiful autumn colors.', 'Красивые осенние цвета.'),
  c('en-na-020', 10, 'winter', 'зима', '❄️', 'Cold winter evenings.', 'Холодные зимние вечера.'),

  // ===== Region 11: Phrases =====
  c('en-fr-001', 11, 'I like it', 'мне нравится', '❤️', 'I really like this place!', 'Мне очень нравится это место!'),
  c('en-fr-002', 11, "I don't like it", 'мне не нравится', '💔', "I don't like this food.", 'Мне не нравится эта еда.'),
  c('en-fr-003', 11, "I'm hungry", 'я голоден/голодна', '🤤', "I'm very hungry!", 'Я очень голоден!'),
  c('en-fr-004', 11, "I'm thirsty", 'я хочу пить', '💧', "I'm thirsty. Water, please.", 'Я хочу пить. Воды, пожалуйста.'),
  c('en-fr-005', 11, "I'm tired", 'я устал/устала', '😴', "I'm so tired today.", 'Я так устал сегодня.'),
  c('en-fr-006', 11, "let's go!", 'пошли!, поехали!', '🚀', "Let's go to the park!", 'Пошли в парк!'),
  c('en-fr-007', 11, 'wait a moment', 'подожди минуту', '⏳', 'Wait a moment, please.', 'Подожди минуту, пожалуйста.'),
  c('en-fr-008', 11, 'I agree', 'я согласен/согласна', '✅', 'I totally agree with you.', 'Я полностью согласен с тобой.'),
  c('en-fr-009', 11, 'no problem', 'без проблем', '👍', 'No problem at all!', 'Вообще без проблем!'),
  c('en-fr-010', 11, 'can you help me?', 'можешь мне помочь?', '🙏', 'Excuse me, can you help me?', 'Извините, вы можете мне помочь?'),
  c('en-fr-011', 11, 'where is...?', 'где находится...?', '📍', 'Where is the subway?', 'Где метро?'),
  c('en-fr-012', 11, 'how much does it cost?', 'сколько это стоит?', '💰', 'How much does it cost?', 'Сколько это стоит?'),
  c('en-fr-013', 11, 'I would like...', 'я бы хотел/хотела...', '🙋', 'I would like a table for two.', 'Я бы хотел столик на двоих.'),
  c('en-fr-014', 11, 'what time is it?', 'который час?', '⏰', 'Excuse me, what time is it?', 'Извините, который час?'),
  c('en-fr-015', 11, 'is there...?', 'есть ли здесь...?', '❓', 'Is there a café nearby?', 'Есть ли поблизости кафе?'),
  c('en-fr-016', 11, 'I live in...', 'я живу в...', '🏠', 'I live in Moscow.', 'Я живу в Москве.'),
  c('en-fr-017', 11, 'have a good day!', 'хорошего дня!', '☀️', 'Have a great day!', 'Хорошего дня!'),
  c('en-fr-018', 11, 'good luck!', 'удачи!', '🍀', 'Good luck on your exam!', 'Удачи на экзамене!'),
  c('en-fr-019', 11, 'congratulations!', 'поздравляю!', '🎉', 'Congratulations on your birthday!', 'Поздравляю с днём рождения!'),
  c('en-fr-020', 11, "don't worry", 'не беспокойся', '😌', "Don't worry, everything is fine.", 'Не беспокойся, всё в порядке.'),

  // ===== Region 12: Beauty / Personal =====
  c('en-be-001', 12, 'beautiful', 'красивый/красивая', '✨', 'What a beautiful place!', 'Какое красивое место!'),
  c('en-be-002', 12, 'handsome', 'красивый (о мужчине)', '😎', 'He is very handsome.', 'Он очень красивый.'),
  c('en-be-003', 12, 'makeup', 'макияж, косметика', '💄', 'She wears beautiful makeup.', 'На ней красивый макияж.'),
  c('en-be-004', 12, 'perfume', 'духи, парфюм', '🌸', 'This perfume smells amazing.', 'Эти духи пахнут восхитительно.'),
  c('en-be-005', 12, 'mirror', 'зеркало', '🪞', 'Look in the mirror.', 'Посмотри в зеркало.'),
  c('en-be-006', 12, 'hairstyle', 'причёска', '💇', 'A beautiful hairstyle.', 'Красивая причёска.'),
  c('en-be-007', 12, 'nail polish', 'лак для ногтей', '💅', 'Red nail polish.', 'Красный лак для ногтей.'),
  c('en-be-008', 12, 'shampoo', 'шампунь', '🧴', 'A gentle shampoo.', 'Мягкий шампунь.'),
  c('en-be-009', 12, 'elegant', 'элегантный/элегантная', '🥂', 'She looks very elegant.', 'Она выглядит очень элегантно.'),
  c('en-be-010', 12, 'stylish', 'стильный/стильная', '👗', 'A stylish outfit.', 'Стильный наряд.'),
  c('en-be-011', 12, 'lipstick', 'губная помада', '💄', 'Red lipstick.', 'Красная помада.'),
  c('en-be-012', 12, 'cream', 'крем', '🧴', 'Face cream.', 'Крем для лица.'),
  c('en-be-013', 12, 'to look good', 'хорошо выглядеть', '✨', 'You look great today!', 'Ты сегодня отлично выглядишь!'),
  c('en-be-014', 12, 'to dress up', 'принарядиться', '👗', 'She dressed up beautifully.', 'Она красиво оделась.'),
  c('en-be-015', 12, 'smile', 'улыбка', '😊', 'What a beautiful smile!', 'Какая красивая улыбка!'),

  // ===== Region 13: Love / Emotions =====
  c('en-am-001', 13, 'love', 'любовь', '❤️', 'Love is beautiful.', 'Любовь прекрасна.'),
  c('en-am-002', 13, 'kiss', 'поцелуй', '😘', 'A good morning kiss.', 'Утренний поцелуй.'),
  c('en-am-003', 13, 'hug', 'объятие', '🤗', 'Give me a hug.', 'Обними меня.'),
  c('en-am-004', 13, 'happy', 'счастливый, радостный', '😊', "I'm very happy today!", 'Я очень счастлив сегодня!'),
  c('en-am-005', 13, 'sad', 'грустный, печальный', '😢', 'Why are you sad?', 'Почему тебе грустно?'),
  c('en-am-006', 13, 'angry', 'злой, сердитый', '😠', "Don't be angry.", 'Не злись.'),
  c('en-am-007', 13, 'afraid', 'напуган, боится', '😨', "Don't be afraid.", 'Не бойся.'),
  c('en-am-008', 13, 'surprised', 'удивлённый', '😮', "I'm so surprised!", 'Я так удивлён!'),
  c('en-am-009', 13, 'lonely', 'одинокий', '🥺', 'I feel lonely.', 'Мне одиноко.'),
  c('en-am-010', 13, 'I love you', 'я люблю тебя', '❤️', 'I love you so much.', 'Я люблю тебя так сильно.'),
  c('en-am-011', 13, 'I miss you', 'я скучаю по тебе', '💔', 'I miss you every day.', 'Я скучаю по тебе каждый день.'),
  c('en-am-012', 13, 'you are wonderful', 'ты замечательный/ная', '🌟', 'You are absolutely wonderful!', 'Ты абсолютно замечательный!'),
  c('en-am-013', 13, 'be mine', 'будь моим/моей', '💝', 'Please be mine forever.', 'Пожалуйста, будь моей навсегда.'),
  c('en-am-014', 13, 'darling', 'дорогой, милый', '🥰', 'Good morning, darling!', 'Доброе утро, дорогой!'),
  c('en-am-015', 13, 'forever', 'навсегда', '♾️', 'Friends forever.', 'Друзья навсегда.'),
  c('en-am-016', 13, 'heart', 'сердце', '❤️', 'You are in my heart.', 'Ты в моём сердце.'),
  c('en-am-017', 13, 'romantic', 'романтичный', '🕯️', 'A romantic dinner.', 'Романтический ужин.'),
  c('en-am-018', 13, 'excited', 'взволнованный', '🤩', "I'm so excited!", 'Я так взволнован!'),
  c('en-am-019', 13, 'jealous', 'ревнивый', '😤', "Don't be jealous.", 'Не ревнуй.'),
  c('en-am-020', 13, 'beautiful person', 'прекрасный человек', '🌹', 'You are a beautiful person.', 'Ты прекрасный человек.'),
];
