// ============================================================
//  German vocabulary cards (German ↔ Russian)
//  Field "es" = German word/phrase, "exEs" = German example
// ============================================================
const c = (id, region, es, ru, emoji, exEs, exRu) => ({ id, region, es, ru, emoji, exEs, exRu });

export const CARDS = [
  // ===== Region 1: Greetings =====
  c('de-s-001', 1, 'Hallo', 'привет, здравствуй', '👋', 'Hallo, wie geht es dir?', 'Привет, как дела?'),
  c('de-s-002', 1, 'Auf Wiedersehen', 'до свидания', '👋', 'Auf Wiedersehen, bis bald!', 'До свидания, до скорой встречи!'),
  c('de-s-003', 1, 'Guten Morgen', 'доброе утро', '🌅', 'Guten Morgen, alle zusammen!', 'Доброе утро всем!'),
  c('de-s-004', 1, 'Guten Tag', 'добрый день', '☀️', 'Guten Tag, mein Herr.', 'Добрый день, господин.'),
  c('de-s-005', 1, 'Guten Abend', 'добрый вечер', '🌙', 'Guten Abend! Willkommen.', 'Добрый вечер! Добро пожаловать.'),
  c('de-s-006', 1, 'Ja', 'да', '✅', 'Ja, natürlich!', 'Да, конечно!'),
  c('de-s-007', 1, 'Nein', 'нет', '❌', 'Nein, danke.', 'Нет, спасибо.'),
  c('de-s-008', 1, 'Danke', 'спасибо', '🙏', 'Danke sehr!', 'Большое спасибо!'),
  c('de-s-009', 1, 'Bitte', 'пожалуйста', '😊', 'Bitte, kein Problem.', 'Пожалуйста, без проблем.'),
  c('de-s-010', 1, 'Entschuldigung', 'извините', '😶', 'Entschuldigung, ich habe Sie nicht gehört.', 'Извините, я вас не слышал.'),
  c('de-s-011', 1, 'Es tut mir leid', 'мне жаль, сожалею', '😔', 'Es tut mir wirklich leid.', 'Мне очень жаль.'),
  c('de-s-012', 1, 'Sprechen Sie langsamer', 'говорите помедленнее', '🐢', 'Bitte sprechen Sie langsamer.', 'Говорите помедленнее, пожалуйста.'),
  c('de-s-013', 1, 'Wie geht es Ihnen?', 'как дела? (вежливо)', '🤔', 'Hallo! Wie geht es Ihnen heute?', 'Привет! Как дела сегодня?'),
  c('de-s-014', 1, 'Mir geht es gut', 'мне хорошо, я в порядке', '👍', 'Mir geht es gut, danke!', 'Мне хорошо, спасибо!'),
  c('de-s-015', 1, 'Nicht so gut', 'не очень хорошо', '👎', 'Heute geht es mir nicht so gut.', 'Мне сегодня нехорошо.'),
  c('de-s-016', 1, 'So lala', 'так себе', '🤷', '— Wie geht es dir? — So lala.', '— Как дела? — Так себе.'),
  c('de-s-017', 1, 'Und Ihnen?', 'а вам?', '🔄', 'Gut, und Ihnen?', 'Хорошо, а вам?'),
  c('de-s-018', 1, 'Freut mich', 'приятно познакомиться', '🤝', 'Freut mich, ich bin Max.', 'Приятно познакомиться, я Макс.'),
  c('de-s-019', 1, 'Wie heißen Sie?', 'как вас зовут?', '🪪', 'Wie heißen Sie, bitte?', 'Как вас зовут, пожалуйста?'),
  c('de-s-020', 1, 'Ich heiße...', 'меня зовут...', '🗣️', 'Ich heiße Anna.', 'Меня зовут Анна.'),
  c('de-s-021', 1, 'Bis später', 'до встречи', '✌️', 'Bis später, Leute!', 'До встречи, ребята!'),
  c('de-s-022', 1, 'Bis morgen', 'до завтра', '📅', 'Bis morgen bei der Arbeit.', 'До завтра на работе.'),
  c('de-s-023', 1, 'Natürlich', 'конечно', '💡', 'Natürlich, kein Problem!', 'Конечно, без проблем!'),
  c('de-s-024', 1, 'Ich verstehe nicht', 'я не понимаю', '😕', 'Entschuldigung, ich verstehe nicht.', 'Извините, я не понимаю.'),
  c('de-s-025', 1, 'Sprechen Sie Russisch?', 'вы говорите по-русски?', '🇷🇺', 'Sprechen Sie Russisch?', 'Вы говорите по-русски?'),
  c('de-s-026', 1, 'Ein bisschen', 'немного', '🤏', 'Ich spreche ein bisschen Deutsch.', 'Я немного говорю по-немецки.'),
  c('de-s-027', 1, 'Was?', 'что?', '❓', 'Was haben Sie gesagt?', 'Что вы сказали?'),
  c('de-s-028', 1, 'Wo?', 'где?', '📍', 'Wo sind Sie?', 'Где вы?'),
  c('de-s-029', 1, 'Wann?', 'когда?', '⏰', 'Wann kommen Sie an?', 'Когда вы приедете?'),
  c('de-s-030', 1, 'Warum?', 'почему?', '🤨', 'Warum nicht?', 'Почему нет?'),
  c('de-s-031', 1, 'Wie?', 'как?', '🔧', 'Wie sagt man das?', 'Как это сказать?'),
  c('de-s-032', 1, 'Wie viel?', 'сколько?', '🔢', 'Wie viel kostet das?', 'Сколько это стоит?'),
  c('de-s-033', 1, 'Hilfe!', 'помогите!', '🆘', 'Hilfe, bitte!', 'Помогите, пожалуйста!'),
  c('de-s-034', 1, 'Prost!', 'за здоровье!', '🥂', 'Prost, alle zusammen!', 'За здоровье всех!'),
  c('de-s-035', 1, 'Willkommen!', 'добро пожаловать!', '🎉', 'Willkommen in unserer Stadt!', 'Добро пожаловать в наш город!'),

  // ===== Region 2: Numbers / Time =====
  c('de-n-001', 2, 'null', 'ноль', '0️⃣', 'null Grad', 'ноль градусов'),
  c('de-n-002', 2, 'eins', 'один', '1️⃣', 'einen Kaffee, bitte', 'один кофе, пожалуйста'),
  c('de-n-003', 2, 'zwei', 'два', '2️⃣', 'zwei Fahrkarten', 'два билета'),
  c('de-n-004', 2, 'drei', 'три', '3️⃣', 'drei Tage', 'три дня'),
  c('de-n-005', 2, 'vier', 'четыре', '4️⃣', 'vier Personen', 'четыре человека'),
  c('de-n-006', 2, 'fünf', 'пять', '5️⃣', 'fünf Euro', 'пять евро'),
  c('de-n-007', 2, 'sechs', 'шесть', '6️⃣', 'sechs Stunden', 'шесть часов'),
  c('de-n-008', 2, 'sieben', 'семь', '7️⃣', 'sieben Tage', 'семь дней'),
  c('de-n-009', 2, 'acht', 'восемь', '8️⃣', 'acht Jahre', 'восемь лет'),
  c('de-n-010', 2, 'neun', 'девять', '9️⃣', 'neun Monate', 'девять месяцев'),
  c('de-n-011', 2, 'zehn', 'десять', '🔟', 'zehn Minuten', 'десять минут'),
  c('de-n-012', 2, 'zwanzig', 'двадцать', '🔢', 'zwanzig Minuten', 'двадцать минут'),
  c('de-n-013', 2, 'dreißig', 'тридцать', '🔢', 'dreißig Tage', 'тридцать дней'),
  c('de-n-014', 2, 'hundert', 'сто', '💯', 'hundert Prozent', 'сто процентов'),
  c('de-n-015', 2, 'Montag', 'понедельник', '📅', 'Bis Montag.', 'До понедельника.'),
  c('de-n-016', 2, 'Dienstag', 'вторник', '📅', 'Das Treffen ist am Dienstag.', 'Встреча во вторник.'),
  c('de-n-017', 2, 'Mittwoch', 'среда', '📅', 'Bis Mittwoch.', 'До среды.'),
  c('de-n-018', 2, 'Donnerstag', 'четверг', '📅', 'Bis Donnerstag.', 'До четверга.'),
  c('de-n-019', 2, 'Freitag', 'пятница', '🎉', 'Endlich Freitag!', 'Наконец-то пятница!'),
  c('de-n-020', 2, 'Samstag', 'суббота', '😎', 'Am Samstag gehen wir aus.', 'В субботу мы выходим.'),
  c('de-n-021', 2, 'Sonntag', 'воскресенье', '☀️', 'Sonntag ist mein freier Tag.', 'Воскресенье — мой выходной.'),
  c('de-n-022', 2, 'heute', 'сегодня', '📆', 'Was ist heute für ein Datum?', 'Какое сегодня число?'),
  c('de-n-023', 2, 'gestern', 'вчера', '⏮️', 'Ich war gestern im Fitnessstudio.', 'Я вчера ходил в зал.'),
  c('de-n-024', 2, 'morgen', 'завтра', '⏭️', 'Bis morgen!', 'До завтра!'),
  c('de-n-025', 2, 'der Morgen', 'утро', '🌅', 'Guten Morgen!', 'Доброе утро!'),
  c('de-n-026', 2, 'der Abend', 'вечер', '🌆', 'Guten Abend!', 'Добрый вечер!'),
  c('de-n-027', 2, 'die Nacht', 'ночь', '🌙', 'Gute Nacht!', 'Спокойной ночи!'),
  c('de-n-028', 2, 'die Stunde', 'час', '⏰', 'Eine Stunde, bitte.', 'Один час, пожалуйста.'),
  c('de-n-029', 2, 'die Minute', 'минута', '⏱️', 'Nur eine Minute!', 'Одну минуту!'),
  c('de-n-030', 2, 'die Woche', 'неделя', '📅', 'Bis nächste Woche.', 'До следующей недели.'),
  c('de-n-031', 2, 'das Jahr', 'год', '🎊', 'Frohes neues Jahr!', 'С Новым годом!'),

  // ===== Region 3: Grammar / Basic =====
  c('de-b-001', 3, 'Ich bin', 'я (есть)', '🧑', 'Ich bin aus Russland.', 'Я из России.'),
  c('de-b-002', 3, 'Sie sind', 'вы (есть)', '👤', 'Sie sind sehr freundlich.', 'Вы очень доброжелательны.'),
  c('de-b-003', 3, 'er ist', 'он (есть)', '👨', 'Er ist mein Freund.', 'Он мой друг.'),
  c('de-b-004', 3, 'sie ist', 'она (есть)', '👩', 'Sie ist Ärztin.', 'Она врач.'),
  c('de-b-005', 3, 'wir sind', 'мы (есть)', '👥', 'Wir sind glücklich.', 'Мы счастливы.'),
  c('de-b-006', 3, 'sie sind', 'они (есть)', '👫', 'Sie sind meine Freunde.', 'Они мои друзья.'),
  c('de-b-007', 3, 'Ich habe', 'у меня есть', '✋', 'Ich habe eine Frage.', 'У меня есть вопрос.'),
  c('de-b-008', 3, 'Ich möchte', 'я хочу', '🙋', 'Ich möchte einen Kaffee, bitte.', 'Я хочу кофе, пожалуйста.'),
  c('de-b-009', 3, 'Ich kann', 'я могу', '💪', 'Ich kann Deutsch sprechen.', 'Я могу говорить по-немецки.'),
  c('de-b-010', 3, 'Ich brauche', 'мне нужно', '📌', 'Ich brauche Hilfe.', 'Мне нужна помощь.'),
  c('de-b-011', 3, 'Ich mag', 'мне нравится', '❤️', 'Ich mag Pizza.', 'Мне нравится пицца.'),
  c('de-b-012', 3, 'Ich weiß', 'я знаю', '💡', 'Ich weiß dieses Wort.', 'Я знаю это слово.'),
  c('de-b-013', 3, 'sehr', 'очень', '‼️', 'Sehr gut!', 'Очень хорошо!'),
  c('de-b-014', 3, 'auch', 'тоже, также', '➕', 'Ich mag auch Tee.', 'Я тоже люблю чай.'),
  c('de-b-015', 3, 'nicht', 'не', '🚫', 'Ich spreche kein Englisch.', 'Я не говорю по-английски.'),
  c('de-b-016', 3, 'und', 'и', '&', 'Tee und Kaffee.', 'Чай и кофе.'),
  c('de-b-017', 3, 'aber', 'но', '⚡', 'Schön, aber teuer.', 'Красиво, но дорого.'),
  c('de-b-018', 3, 'oder', 'или', '🔀', 'Kaffee oder Tee?', 'Кофе или чай?'),

  // ===== Region 4: Family =====
  c('de-f-001', 4, 'die Mutter', 'мама, мать', '👩', 'Meine Mutter ist Lehrerin.', 'Моя мама — учитель.'),
  c('de-f-002', 4, 'der Vater', 'папа, отец', '👨', 'Mein Vater ist groß.', 'Мой папа высокий.'),
  c('de-f-003', 4, 'der Bruder', 'брат', '👦', 'Ich habe einen Bruder.', 'У меня есть один брат.'),
  c('de-f-004', 4, 'die Schwester', 'сестра', '👧', 'Meine Schwester ist älter.', 'Моя сестра старше меня.'),
  c('de-f-005', 4, 'der Sohn', 'сын', '👦', 'Er ist mein Sohn.', 'Он мой сын.'),
  c('de-f-006', 4, 'die Tochter', 'дочь', '👧', 'Sie ist meine Tochter.', 'Она моя дочь.'),
  c('de-f-007', 4, 'die Großmutter', 'бабушка', '👵', 'Meine Großmutter ist sehr nett.', 'Моя бабушка очень добрая.'),
  c('de-f-008', 4, 'der Großvater', 'дедушка', '👴', 'Mein Großvater liebt Angeln.', 'Мой дедушка любит рыбалку.'),
  c('de-f-009', 4, 'der Onkel', 'дядя', '🧔', 'Mein Onkel wohnt in Berlin.', 'Мой дядя живёт в Берлине.'),
  c('de-f-010', 4, 'die Tante', 'тётя', '👱‍♀️', 'Meine Tante backt leckere Kuchen.', 'Моя тётя печёт вкусные торты.'),
  c('de-f-011', 4, 'der Mann', 'муж', '💑', 'Mein Mann ist lustig.', 'Мой муж смешной.'),
  c('de-f-012', 4, 'die Frau', 'жена', '💑', 'Meine Frau ist schön.', 'Моя жена красивая.'),
  c('de-f-013', 4, 'das Baby', 'малыш', '👶', 'Das Baby schläft.', 'Малыш спит.'),
  c('de-f-014', 4, 'die Familie', 'семья', '👨‍👩‍👧', 'Ich liebe meine Familie.', 'Я люблю свою семью.'),
  c('de-f-015', 4, 'die Eltern', 'родители', '👨‍👩‍👧', 'Meine Eltern wohnen in Moskau.', 'Мои родители живут в Москве.'),
  c('de-f-016', 4, 'die Kinder', 'дети', '👶', 'Sie haben zwei Kinder.', 'У них двое детей.'),
  c('de-f-017', 4, 'der Freund', 'друг, парень', '🤝', 'Er ist mein bester Freund.', 'Он мой лучший друг.'),
  c('de-f-018', 4, 'die Freundin', 'подруга, девушка', '🤝', 'Sie ist meine Freundin.', 'Она моя подруга.'),
  c('de-f-019', 4, 'der Nachbar', 'сосед', '🏘️', 'Mein Nachbar ist sehr nett.', 'Мой сосед очень приятный.'),

  // ===== Region 5: Food =====
  c('de-c-001', 5, 'das Wasser', 'вода', '💧', 'Ein Glas Wasser, bitte.', 'Стакан воды, пожалуйста.'),
  c('de-c-002', 5, 'der Kaffee', 'кофе', '☕', 'Ich trinke jeden Morgen Kaffee.', 'Я пью кофе каждое утро.'),
  c('de-c-003', 5, 'der Tee', 'чай', '🍵', 'Möchten Sie Tee?', 'Хотите чаю?'),
  c('de-c-004', 5, 'der Saft', 'сок', '🍊', 'Orangensaft, bitte.', 'Апельсиновый сок, пожалуйста.'),
  c('de-c-005', 5, 'die Milch', 'молоко', '🥛', 'Ich mag kalte Milch.', 'Я люблю холодное молоко.'),
  c('de-c-006', 5, 'das Brot', 'хлеб', '🍞', 'Frisches Brot ist lecker.', 'Свежий хлеб вкусный.'),
  c('de-c-007', 5, 'die Butter', 'масло', '🧈', 'Brot mit Butter.', 'Хлеб с маслом.'),
  c('de-c-008', 5, 'der Käse', 'сыр', '🧀', 'Ich liebe Käse.', 'Я люблю сыр.'),
  c('de-c-009', 5, 'das Fleisch', 'мясо', '🥩', 'Dieses Fleisch ist sehr gut.', 'Это мясо очень хорошее.'),
  c('de-c-010', 5, 'das Hähnchen', 'курица', '🍗', 'Gegrilltes Hähnchen, bitte.', 'Курица-гриль, пожалуйста.'),
  c('de-c-011', 5, 'der Fisch', 'рыба', '🐟', 'Ich liebe frischen Fisch.', 'Я люблю свежую рыбу.'),
  c('de-c-012', 5, 'der Reis', 'рис', '🍚', 'Reis mit Gemüse.', 'Рис с овощами.'),
  c('de-c-013', 5, 'die Nudeln', 'лапша, макароны', '🍝', 'Nudeln mit Tomatensoße.', 'Паста с томатным соусом.'),
  c('de-c-014', 5, 'der Salat', 'салат', '🥗', 'Einen frischen Salat, bitte.', 'Свежий салат, пожалуйста.'),
  c('de-c-015', 5, 'die Suppe', 'суп', '🍲', 'Heiße Suppe wärmt.', 'Горячий суп согревает.'),
  c('de-c-016', 5, 'der Apfel', 'яблоко', '🍎', 'Ein Apfel am Tag ist gesund.', 'Яблоко в день — полезно.'),
  c('de-c-017', 5, 'die Orange', 'апельсин', '🍊', 'Frischer Orangensaft.', 'Свежий апельсиновый сок.'),
  c('de-c-018', 5, 'die Banane', 'банан', '🍌', 'Ich esse täglich eine Banane.', 'Я ем банан каждый день.'),
  c('de-c-019', 5, 'der Kuchen', 'торт, пирог', '🎂', 'Ein Stück Kuchen, bitte.', 'Кусочек торта, пожалуйста.'),
  c('de-c-020', 5, 'die Pizza', 'пицца', '🍕', 'Pizza ist mein Lieblingsessen.', 'Пицца — моя любимая еда.'),
  c('de-c-021', 5, 'das Ei', 'яйцо', '🥚', 'Spiegeleier zum Frühstück.', 'Яичница на завтрак.'),
  c('de-c-022', 5, 'das Gemüse', 'овощи', '🥦', 'Frisches Gemüse ist gesund.', 'Свежие овощи полезны.'),
  c('de-c-023', 5, 'das Frühstück', 'завтрак', '🍳', 'Ich frühstücke um 8 Uhr.', 'Я завтракаю в 8.'),

  // ===== Region 6: City =====
  c('de-ci-001', 6, 'die Straße', 'улица', '🛣️', 'Welche Straße ist das?', 'Какая это улица?'),
  c('de-ci-002', 6, 'das Haus', 'дом', '🏠', 'Ich wohne in einem großen Haus.', 'Я живу в большом доме.'),
  c('de-ci-003', 6, 'der Bus', 'автобус', '🚌', 'Nehmen Sie den Bus Nummer 5.', 'Садитесь на автобус №5.'),
  c('de-ci-004', 6, 'das Auto', 'машина', '🚗', 'Ich fahre mit dem Auto.', 'Я еду на машине.'),
  c('de-ci-005', 6, 'die U-Bahn', 'метро', '🚇', 'Fahren Sie mit der U-Bahn in die Stadt.', 'Доехать на метро до центра.'),
  c('de-ci-006', 6, 'das Taxi', 'такси', '🚕', 'Rufen Sie bitte ein Taxi.', 'Вызовите такси, пожалуйста.'),
  c('de-ci-007', 6, 'der Flughafen', 'аэропорт', '✈️', 'Der Flughafen ist weit.', 'Аэропорт далеко.'),
  c('de-ci-008', 6, 'das Hotel', 'отель, гостиница', '🏨', 'Ich brauche ein Hotelzimmer.', 'Мне нужен номер в отеле.'),
  c('de-ci-009', 6, 'das Restaurant', 'ресторан', '🍽️', 'Gehen wir ins Restaurant.', 'Давай пойдём в ресторан.'),
  c('de-ci-010', 6, 'das Café', 'кафе', '☕', 'Treffen wir uns im Café.', 'Давай встретимся в кафе.'),
  c('de-ci-011', 6, 'der Laden', 'магазин', '🛍️', 'Der Laden ist geschlossen.', 'Магазин закрыт.'),
  c('de-ci-012', 6, 'die Schule', 'школа', '🏫', 'Meine Schule ist in der Nähe.', 'Моя школа рядом.'),
  c('de-ci-013', 6, 'das Krankenhaus', 'больница', '🏥', 'Das Krankenhaus ist in der Hauptstraße.', 'Больница на Главной улице.'),
  c('de-ci-014', 6, 'die Bank', 'банк', '🏦', 'Ich muss zur Bank.', 'Мне нужно в банк.'),
  c('de-ci-015', 6, 'der Park', 'парк', '🌳', 'Gehen wir im Park spazieren.', 'Давай прогуляемся в парке.'),
  c('de-ci-016', 6, 'die Apotheke', 'аптека', '💊', 'Gibt es eine Apotheke in der Nähe?', 'Есть поблизости аптека?'),
  c('de-ci-017', 6, 'links', 'налево, слева', '⬅️', 'Biegen Sie hier links ab.', 'Поверни налево здесь.'),
  c('de-ci-018', 6, 'rechts', 'направо, справа', '➡️', 'Die Bank ist rechts.', 'Банк справа.'),
  c('de-ci-019', 6, 'geradeaus', 'прямо', '⬆️', 'Gehen Sie geradeaus.', 'Иди прямо.'),
  c('de-ci-020', 6, 'nah / in der Nähe', 'близко, рядом', '📍', 'Es ist ganz nah.', 'Это очень близко.'),

  // ===== Region 7: Shopping =====
  c('de-sh-001', 7, 'kaufen', 'купить', '🛒', 'Ich möchte ein Hemd kaufen.', 'Я хочу купить рубашку.'),
  c('de-sh-002', 7, 'der Preis', 'цена', '💰', 'Was ist der Preis?', 'Какая цена?'),
  c('de-sh-003', 7, 'teuer', 'дорогой', '💸', 'Das ist zu teuer.', 'Это слишком дорого.'),
  c('de-sh-004', 7, 'billig', 'дешёвый', '🤑', 'Das ist sehr billig!', 'Это очень дёшево!'),
  c('de-sh-005', 7, 'die Größe', 'размер', '📏', 'Welche Größe haben Sie?', 'Какой у вас размер?'),
  c('de-sh-006', 7, 'klein', 'маленький', '🔽', 'Das ist zu klein.', 'Это слишком маленькое.'),
  c('de-sh-007', 7, 'groß', 'большой', '🔼', 'Haben Sie eine größere Größe?', 'Есть размер побольше?'),
  c('de-sh-008', 7, 'schwarz', 'чёрный', '⚫', 'Schwarze Schuhe.', 'Чёрные туфли.'),
  c('de-sh-009', 7, 'weiß', 'белый', '⚪', 'Ein weißes Kleid.', 'Белое платье.'),
  c('de-sh-010', 7, 'rot', 'красный', '🔴', 'Ein roter Mantel.', 'Красное пальто.'),
  c('de-sh-011', 7, 'blau', 'синий, голубой', '🔵', 'Eine blaue Jacke.', 'Синяя куртка.'),
  c('de-sh-012', 7, 'grün', 'зелёный', '🟢', 'Grüne Schuhe.', 'Зелёные туфли.'),
  c('de-sh-013', 7, 'gelb', 'жёлтый', '🟡', 'Eine gelbe Tasche.', 'Жёлтая сумка.'),
  c('de-sh-014', 7, 'das T-Shirt', 'футболка', '👕', 'Ich brauche ein neues T-Shirt.', 'Мне нужна новая футболка.'),
  c('de-sh-015', 7, 'die Hose', 'штаны, брюки', '👖', 'Diese Hose passt gut.', 'Эти брюки хорошо сидят.'),
  c('de-sh-016', 7, 'das Kleid', 'платье', '👗', 'Ein schönes Kleid.', 'Красивое платье.'),
  c('de-sh-017', 7, 'die Schuhe', 'туфли, обувь', '👟', 'Neue Schuhe für die Party.', 'Новые туфли на вечеринку.'),
  c('de-sh-018', 7, 'die Jacke', 'куртка, пиджак', '🧥', 'Eine warme Jacke.', 'Тёплая куртка.'),
  c('de-sh-019', 7, 'die Tasche', 'сумка', '👜', 'Eine Ledertasche.', 'Кожаная сумка.'),
  c('de-sh-020', 7, 'der Rabatt', 'скидка', '🏷️', 'Gibt es einen Rabatt?', 'Есть скидка?'),

  // ===== Region 8: Home =====
  c('de-h-001', 8, 'die Wohnung', 'квартира', '🏢', 'Ich wohne in einer Wohnung.', 'Я живу в квартире.'),
  c('de-h-002', 8, 'das Zimmer', 'комната', '🚪', 'Das ist ein großes Zimmer.', 'Это большая комната.'),
  c('de-h-003', 8, 'das Schlafzimmer', 'спальня', '🛏️', 'Das Schlafzimmer ist ruhig.', 'Спальня тихая.'),
  c('de-h-004', 8, 'das Badezimmer', 'ванная, туалет', '🚿', 'Wo ist das Badezimmer?', 'Где ванная?'),
  c('de-h-005', 8, 'die Küche', 'кухня', '🍳', 'Ich koche in der Küche.', 'Я готовлю на кухне.'),
  c('de-h-006', 8, 'das Wohnzimmer', 'гостиная', '🛋️', 'Sitzen wir im Wohnzimmer.', 'Давай посидим в гостиной.'),
  c('de-h-007', 8, 'der Tisch', 'стол', '🪑', 'Die Schlüssel liegen auf dem Tisch.', 'Ключи на столе.'),
  c('de-h-008', 8, 'der Stuhl', 'стул', '🪑', 'Bitte setzen Sie sich auf diesen Stuhl.', 'Пожалуйста, сядьте на этот стул.'),
  c('de-h-009', 8, 'das Bett', 'кровать', '🛏️', 'Das Bett ist bequem.', 'Кровать удобная.'),
  c('de-h-010', 8, 'das Fenster', 'окно', '🪟', 'Öffne das Fenster, bitte.', 'Открой окно, пожалуйста.'),
  c('de-h-011', 8, 'die Tür', 'дверь', '🚪', 'Mach die Tür zu.', 'Закрой дверь.'),
  c('de-h-012', 8, 'der Kühlschrank', 'холодильник', '🧊', 'Die Milch ist im Kühlschrank.', 'Молоко в холодильнике.'),
  c('de-h-013', 8, 'das Sofa', 'диван', '🛋️', 'Setz dich auf das Sofa.', 'Садись на диван.'),
  c('de-h-014', 8, 'die Lampe', 'лампа', '💡', 'Mach die Lampe an.', 'Включи лампу.'),
  c('de-h-015', 8, 'der Fernseher', 'телевизор', '📺', 'Was läuft heute im Fernsehen?', 'Что сегодня по телевизору?'),
  c('de-h-016', 8, 'der Schlüssel', 'ключ', '🔑', 'Ich finde meinen Schlüssel nicht.', 'Я не могу найти свой ключ.'),
  c('de-h-017', 8, 'die Wand', 'стена', '🧱', 'Das Bild hängt an der Wand.', 'Картина на стене.'),

  // ===== Region 9: Body / Health =====
  c('de-cu-001', 9, 'der Kopf', 'голова', '🗣️', 'Mein Kopf tut weh.', 'У меня болит голова.'),
  c('de-cu-002', 9, 'das Haar', 'волосы', '💇', 'Sie hat schöne Haare.', 'У неё красивые волосы.'),
  c('de-cu-003', 9, 'das Auge', 'глаз', '👁️', 'Blaue Augen.', 'Голубые глаза.'),
  c('de-cu-004', 9, 'das Ohr', 'ухо', '👂', 'Ich höre mit meinen Ohren.', 'Я слышу ушами.'),
  c('de-cu-005', 9, 'die Nase', 'нос', '👃', 'Meine Nase ist kalt.', 'У меня холодный нос.'),
  c('de-cu-006', 9, 'der Mund', 'рот', '👄', 'Öffne deinen Mund.', 'Открой рот.'),
  c('de-cu-007', 9, 'der Zahn', 'зуб', '🦷', 'Mein Zahn tut weh.', 'У меня болит зуб.'),
  c('de-cu-008', 9, 'die Hand', 'рука', '✋', 'Wasch deine Hände.', 'Помой руки.'),
  c('de-cu-009', 9, 'das Bein', 'нога', '🦵', 'Meine Beine sind müde.', 'Мои ноги устали.'),
  c('de-cu-010', 9, 'der Rücken', 'спина', '🔙', 'Mein Rücken tut weh.', 'У меня болит спина.'),
  c('de-cu-011', 9, 'der Bauch', 'живот', '🫁', 'Ich habe Bauchschmerzen.', 'У меня болит живот.'),
  c('de-cu-012', 9, 'der Arzt', 'врач', '👨‍⚕️', 'Ich muss zum Arzt.', 'Мне нужно к врачу.'),
  c('de-cu-013', 9, 'das Medikament', 'лекарство', '💊', 'Nehmen Sie dieses Medikament.', 'Прими это лекарство.'),
  c('de-cu-014', 9, 'der Schmerz', 'боль', '😣', 'Ich habe hier Schmerzen.', 'Здесь больно.'),
  c('de-cu-015', 9, 'das Fieber', 'жар, температура', '🤒', 'Ich habe Fieber.', 'У меня жар.'),
  c('de-cu-016', 9, 'die Erkältung', 'простуда', '🤧', 'Ich bin erkältet.', 'У меня простуда.'),
  c('de-cu-017', 9, 'Ich fühle mich gut', 'я чувствую себя хорошо', '😊', 'Ich fühle mich heute großartig!', 'Сегодня я чувствую себя отлично!'),
  c('de-cu-018', 9, 'Ich fühle mich schlecht', 'мне плохо', '🤢', 'Ich fühle mich schlecht, ich brauche Ruhe.', 'Мне плохо, нужен отдых.'),
  c('de-cu-019', 9, 'müde', 'усталый', '😴', 'Ich bin sehr müde.', 'Я очень устал.'),
  c('de-cu-020', 9, 'gesund', 'здоровый', '💪', 'Bleib gesund!', 'Будь здоров!'),

  // ===== Region 10: Nature =====
  c('de-na-001', 10, 'der Baum', 'дерево', '🌳', 'Ein großer Baum im Park.', 'Большое дерево в парке.'),
  c('de-na-002', 10, 'die Blume', 'цветок', '🌸', 'Schöne Blumen.', 'Красивые цветы.'),
  c('de-na-003', 10, 'das Gras', 'трава', '🌿', 'Grünes Gras.', 'Зелёная трава.'),
  c('de-na-004', 10, 'der Fluss', 'река', '🏞️', 'Der Fluss ist lang.', 'Река длинная.'),
  c('de-na-005', 10, 'das Meer', 'море', '🌊', 'Ich liebe das Meer.', 'Я люблю море.'),
  c('de-na-006', 10, 'der Berg', 'гора', '⛰️', 'Die Berge sind hoch.', 'Горы высокие.'),
  c('de-na-007', 10, 'der Himmel', 'небо', '☁️', 'Der Himmel ist blau.', 'Небо голубое.'),
  c('de-na-008', 10, 'die Sonne', 'солнце', '☀️', 'Die Sonne scheint.', 'Солнце светит.'),
  c('de-na-009', 10, 'der Mond', 'луна', '🌙', 'Heute ist Vollmond.', 'Сегодня полная луна.'),
  c('de-na-010', 10, 'der Stern', 'звезда', '⭐', 'Ich sehe viele Sterne.', 'Я вижу много звёзд.'),
  c('de-na-011', 10, 'der Regen', 'дождь', '🌧️', 'Es regnet draußen.', 'На улице идёт дождь.'),
  c('de-na-012', 10, 'der Schnee', 'снег', '❄️', 'Der Schnee ist schön.', 'Снег красивый.'),
  c('de-na-013', 10, 'der Wind', 'ветер', '💨', 'Heute ist starker Wind.', 'Сильный ветер сегодня.'),
  c('de-na-014', 10, 'heiß', 'жаркий', '🔥', 'Heute ist es sehr heiß.', 'Сегодня очень жарко.'),
  c('de-na-015', 10, 'kalt', 'холодный', '🧊', 'Draußen ist es sehr kalt.', 'На улице очень холодно.'),
  c('de-na-016', 10, 'warm', 'тёплый', '🌤️', 'Ein warmer Frühlingstag.', 'Тёплый весенний день.'),
  c('de-na-017', 10, 'der Frühling', 'весна', '🌷', 'Der Frühling ist meine Lieblingszeit.', 'Весна — мой любимый сезон.'),
  c('de-na-018', 10, 'der Sommer', 'лето', '☀️', 'Heiße Sommertage.', 'Жаркие летние дни.'),
  c('de-na-019', 10, 'der Herbst', 'осень', '🍂', 'Schöne Herbstfarben.', 'Красивые осенние цвета.'),
  c('de-na-020', 10, 'der Winter', 'зима', '❄️', 'Kalte Winterabende.', 'Холодные зимние вечера.'),

  // ===== Region 11: Phrases =====
  c('de-fr-001', 11, 'Das gefällt mir', 'мне нравится', '❤️', 'Das gefällt mir wirklich!', 'Мне это очень нравится!'),
  c('de-fr-002', 11, 'Das gefällt mir nicht', 'мне не нравится', '💔', 'Das Essen gefällt mir nicht.', 'Мне не нравится эта еда.'),
  c('de-fr-003', 11, 'Ich habe Hunger', 'я голоден/голодна', '🤤', 'Ich habe großen Hunger!', 'Я очень голоден!'),
  c('de-fr-004', 11, 'Ich habe Durst', 'я хочу пить', '💧', 'Ich habe Durst. Wasser, bitte.', 'Я хочу пить. Воды, пожалуйста.'),
  c('de-fr-005', 11, 'Ich bin müde', 'я устал/устала', '😴', 'Ich bin heute so müde.', 'Я так устал сегодня.'),
  c('de-fr-006', 11, 'Gehen wir!', 'пошли!, поехали!', '🚀', 'Gehen wir in den Park!', 'Пошли в парк!'),
  c('de-fr-007', 11, 'Einen Moment', 'подожди минуту', '⏳', 'Einen Moment, bitte.', 'Подожди минуту, пожалуйста.'),
  c('de-fr-008', 11, 'Ich bin einverstanden', 'я согласен/согласна', '✅', 'Ich bin völlig einverstanden.', 'Я полностью согласен.'),
  c('de-fr-009', 11, 'Kein Problem', 'без проблем', '👍', 'Kein Problem überhaupt!', 'Вообще без проблем!'),
  c('de-fr-010', 11, 'Können Sie mir helfen?', 'можете мне помочь?', '🙏', 'Entschuldigung, können Sie mir helfen?', 'Извините, вы можете мне помочь?'),
  c('de-fr-011', 11, 'Wo ist...?', 'где находится...?', '📍', 'Wo ist die U-Bahn?', 'Где метро?'),
  c('de-fr-012', 11, 'Wie viel kostet das?', 'сколько это стоит?', '💰', 'Wie viel kostet das?', 'Сколько это стоит?'),
  c('de-fr-013', 11, 'Ich hätte gern...', 'я бы хотел/хотела...', '🙋', 'Ich hätte gern einen Tisch für zwei.', 'Я бы хотел столик на двоих.'),
  c('de-fr-014', 11, 'Wie spät ist es?', 'который час?', '⏰', 'Entschuldigung, wie spät ist es?', 'Извините, который час?'),
  c('de-fr-015', 11, 'Ich wohne in...', 'я живу в...', '🏠', 'Ich wohne in Moskau.', 'Я живу в Москве.'),
  c('de-fr-016', 11, 'Schönen Tag!', 'хорошего дня!', '☀️', 'Noch einen schönen Tag!', 'Хорошего дня!'),
  c('de-fr-017', 11, 'Viel Glück!', 'удачи!', '🍀', 'Viel Glück bei der Prüfung!', 'Удачи на экзамене!'),
  c('de-fr-018', 11, 'Herzlichen Glückwunsch!', 'поздравляю!', '🎉', 'Herzlichen Glückwunsch zum Geburtstag!', 'Поздравляю с днём рождения!'),
  c('de-fr-019', 11, 'Keine Sorge', 'не беспокойся', '😌', 'Keine Sorge, alles ist gut.', 'Не беспокойся, всё в порядке.'),

  // ===== Region 12: Beauty =====
  c('de-be-001', 12, 'schön', 'красивый/красивая', '✨', 'Was für ein schöner Ort!', 'Какое красивое место!'),
  c('de-be-002', 12, 'gutaussehend', 'красивый (о мужчине)', '😎', 'Er ist sehr gutaussehend.', 'Он очень красивый.'),
  c('de-be-003', 12, 'das Make-up', 'макияж, косметика', '💄', 'Sie trägt schönes Make-up.', 'На ней красивый макияж.'),
  c('de-be-004', 12, 'das Parfüm', 'духи, парфюм', '🌸', 'Dieses Parfüm riecht wunderbar.', 'Эти духи пахнут восхитительно.'),
  c('de-be-005', 12, 'der Spiegel', 'зеркало', '🪞', 'Schau in den Spiegel.', 'Посмотри в зеркало.'),
  c('de-be-006', 12, 'die Frisur', 'причёска', '💇', 'Eine schöne Frisur.', 'Красивая причёска.'),
  c('de-be-007', 12, 'der Nagellack', 'лак для ногтей', '💅', 'Roter Nagellack.', 'Красный лак для ногтей.'),
  c('de-be-008', 12, 'das Shampoo', 'шампунь', '🧴', 'Ein sanftes Shampoo.', 'Мягкий шампунь.'),
  c('de-be-009', 12, 'elegant', 'элегантный/элегантная', '🥂', 'Sie sieht sehr elegant aus.', 'Она выглядит очень элегантно.'),
  c('de-be-010', 12, 'stilvoll', 'стильный/стильная', '👗', 'Ein stilvolles Outfit.', 'Стильный наряд.'),
  c('de-be-011', 12, 'der Lippenstift', 'губная помада', '💄', 'Roter Lippenstift.', 'Красная помада.'),
  c('de-be-012', 12, 'die Creme', 'крем', '🧴', 'Gesichtscreme.', 'Крем для лица.'),
  c('de-be-013', 12, 'das Lächeln', 'улыбка', '😊', 'Was für ein schönes Lächeln!', 'Какая красивая улыбка!'),

  // ===== Region 13: Love / Emotions =====
  c('de-am-001', 13, 'die Liebe', 'любовь', '❤️', 'Die Liebe ist schön.', 'Любовь прекрасна.'),
  c('de-am-002', 13, 'der Kuss', 'поцелуй', '😘', 'Ein Gute-Morgen-Kuss.', 'Утренний поцелуй.'),
  c('de-am-003', 13, 'die Umarmung', 'объятие', '🤗', 'Umarme mich.', 'Обними меня.'),
  c('de-am-004', 13, 'glücklich', 'счастливый, радостный', '😊', 'Ich bin heute sehr glücklich!', 'Я очень счастлив сегодня!'),
  c('de-am-005', 13, 'traurig', 'грустный, печальный', '😢', 'Warum bist du traurig?', 'Почему тебе грустно?'),
  c('de-am-006', 13, 'wütend', 'злой, сердитый', '😠', 'Sei nicht wütend.', 'Не злись.'),
  c('de-am-007', 13, 'ängstlich', 'напуган, боится', '😨', 'Hab keine Angst.', 'Не бойся.'),
  c('de-am-008', 13, 'überrascht', 'удивлённый', '😮', 'Ich bin so überrascht!', 'Я так удивлён!'),
  c('de-am-009', 13, 'einsam', 'одинокий', '🥺', 'Ich fühle mich einsam.', 'Мне одиноко.'),
  c('de-am-010', 13, 'Ich liebe dich', 'я люблю тебя', '❤️', 'Ich liebe dich so sehr.', 'Я люблю тебя так сильно.'),
  c('de-am-011', 13, 'Ich vermisse dich', 'я скучаю по тебе', '💔', 'Ich vermisse dich jeden Tag.', 'Я скучаю по тебе каждый день.'),
  c('de-am-012', 13, 'Du bist wunderbar', 'ты замечательный/ная', '🌟', 'Du bist absolut wunderbar!', 'Ты абсолютно замечательный!'),
  c('de-am-013', 13, 'mein Schatz', 'моя дорогая/мой дорогой', '🥰', 'Guten Morgen, mein Schatz!', 'Доброе утро, дорогой!'),
  c('de-am-014', 13, 'für immer', 'навсегда', '♾️', 'Freunde für immer.', 'Друзья навсегда.'),
  c('de-am-015', 13, 'romantisch', 'романтичный', '🕯️', 'Ein romantisches Abendessen.', 'Романтический ужин.'),
  c('de-am-016', 13, 'aufgeregt', 'взволнованный', '🤩', 'Ich bin so aufgeregt!', 'Я так взволнован!'),
  c('de-am-017', 13, 'eifersüchtig', 'ревнивый', '😤', 'Sei nicht eifersüchtig.', 'Не ревнуй.'),
];
